import Foundation
import CryptoKit

/// Context Compiler (v1.6) — cabecera de sincronización que Pasture escribe al
/// principio de cada destino compilado. Permite distinguir 'lo escribió Pasture y
/// nadie lo tocó' de 'un humano lo editó' SIN estado externo: la cabecera embebe
/// el SHA-256 del cuerpo, y el conflicto se detecta comparando ese hash con el
/// hash del cuerpo actual del fichero.
///
/// CryptoKit es framework de Apple — se preserva la regla de cero dependencias.
public enum SyncMarker {

    /// Prefijo del comentario de cabecera (sintaxis Markdown/HTML).
    static let prefix = "<!-- pasture-pack:"

    /// SHA-256 hex (minúsculas) del texto UTF-8. Determinista → idempotencia.
    public static func sha256(_ text: String) -> String {
        SHA256.hash(data: Data(text.utf8))
            .map { String(format: "%02x", $0) }
            .joined()
    }

    /// Línea de cabecera para un pack + hash del cuerpo. Una sola línea.
    public static func header(packName: String, bodyHash: String) -> String {
        "\(prefix) \(packName) | sha256: \(bodyHash) | generated by Pasture — do not edit -->"
    }

    /// Compone el contenido completo del destino: cabecera + `\n` + cuerpo.
    /// El hash de la cabecera se calcula sobre el cuerpo (no sobre sí misma).
    public static func compose(packName: String, body: String) -> String {
        header(packName: packName, bodyHash: sha256(body)) + "\n" + body
    }

    // MARK: — Parseo

    public struct Parsed: Equatable, Sendable {
        public let packName: String
        public let bodyHash: String
        public let body: String
    }

    /// Extrae cabecera + cuerpo de un fichero. `nil` si la primera línea no es una
    /// cabecera de Pasture (⇒ el llamante lo trata como conflicto: fichero ajeno).
    public static func parse(_ fileContent: String) -> Parsed? {
        if let newline = fileContent.firstIndex(of: "\n") {
            let firstLine = String(fileContent[..<newline])
            guard let head = parseHeaderLine(firstLine) else { return nil }
            let body = String(fileContent[fileContent.index(after: newline)...])
            return Parsed(packName: head.name, bodyHash: head.hash, body: body)
        }
        // Sin salto de línea: solo puede ser una cabecera con cuerpo vacío.
        guard let head = parseHeaderLine(fileContent) else { return nil }
        return Parsed(packName: head.name, bodyHash: head.hash, body: "")
    }

    /// Parseo robusto de una línea de cabecera. Busca los tokens por nombre, no por
    /// posición, así que un nombre de pack con ' | ' no rompe la extracción del hash.
    private static func parseHeaderLine(_ line: String) -> (name: String, hash: String)? {
        guard line.hasPrefix(prefix), line.hasSuffix("-->") else { return nil }

        guard let hashRange = line.range(of: "sha256:") else { return nil }
        let afterHash = line[hashRange.upperBound...].drop(while: { $0 == " " })
        let hash = afterHash.prefix(while: { $0.isHexDigit })
        guard !hash.isEmpty else { return nil }

        guard let nameRange = line.range(of: "pasture-pack:") else { return nil }
        let afterName = line[nameRange.upperBound...]
        let name: Substring
        if let pipe = afterName.range(of: " | ") {
            name = afterName[..<pipe.lowerBound]
        } else {
            name = afterName
        }
        return (String(name).trimmingCharacters(in: .whitespaces), String(hash))
    }

    // MARK: — Estado de sincronización (detección de conflicto)

    public enum SyncState: Equatable, Sendable {
        /// El destino no existe en disco → se puede crear sin diálogo (AC#10).
        case targetMissing
        /// Existe, tiene cabecera de Pasture y el hash del cuerpo coincide → es
        /// exactamente lo que Pasture escribió; sobrescribir es seguro.
        case clean
        /// Existe pero (no tiene cabecera de Pasture) o (el hash no coincide) →
        /// un humano lo tocó; sobrescribir exige confirmación explícita (AC#2).
        case conflict
    }

    /// Decide el estado a partir del contenido actual del destino (`nil` si no existe).
    public static func state(existingFileContent: String?) -> SyncState {
        guard let content = existingFileContent else { return .targetMissing }
        guard let parsed = parse(content) else { return .conflict }
        return sha256(parsed.body) == parsed.bodyHash ? .clean : .conflict
    }
}
